SMACSS
SCALABLE MODULAR CSS



BASE || LAYOUT || MODULES || THEME

RESPONSIVE DESIGN: ADJUST THE SCREEN OR LAYOUT CHANGES. CONTENT MUST ALWAYS STAY THE SAME. 
    DESKTOP TO MOBILE.

BLOCK ELEMENT TAKE ALL SPACE THEY CAN
INLINE ELEMENT TAKE WHAT THEY NEED - CONTENT

YOUR BRAIN CAN ONLY PROCESS SO MUCH. ONLY SO MUCH INFORMATION CAN BE DISPLAYED, SO COLUMNS ARE NECESSARY. 

THEME INVOLVES SPACE
MAKE A SITE DESIGN THAT EVERY PAGE SHARES. 

MEDIA QUERY = //@media(min-width: 960px){
    div{

    }
}

RESET
BASE : core, font, reset, box sizing
LAYOUT: spacing, position
MODULES: rotators
THEME: feels